version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Expose frontend on port 8080
    networks:
      - tc-network  # Same network as backend
    environment:
      - REACT_APP_API_URL=http://app:3001/api  # Use service name "app"

networks:
  tc-network:
    external: true